name: Build and Push Docker image to ghcr

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 1.11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GIITHUB_USERNAME }}
          password: ${{ secrets.GIITHUB_TOKEN }}

      - name: Build with Maven
        run: mvn clean install

      - name: Build Docker image
        run: mvn package -DskipTests jib:build -Dimage=ghcr.io/imkunyoung/ecommerce_application_monolith_server:latest
